/**
 * ${1:Description placeholder}
 *
 * @enum
 */
export enum STORE_KEYS {
  MASTER_DATA = 'MASTER_DATA',
  SCRIPT_ID_INDEX = 'SCRIPT_ID_INDEX',
  SEARCH_STRING_INDEX = 'SEARCH_STRING_INDEX',
  DERIVATIVES_INDEX = 'DERIVATIVES_INDEX',
  ISIN_CODE_INDEX = 'ISIN_CODE_INDEX'
}
